version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"        # matches your working env

# Use a conda env so GDAL/rasterio resolve cleanly on RTD
conda:
  environment: environment-dev.yml   # or environment.yml if you prefer

sphinx:
  configuration: docs/conf.py

# Ensure your package is installed so autodoc + version discovery work
python:
  install:
    - method: pip
      path: .
