name: Upload Python Package

on:
  release:
    types: [published]      # fires when you click "Publish release"
  workflow_dispatch:         # manual run button

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade build tools
        run: python -m pip install --upgrade pip build twine

      - name: Clean build artifacts
        run: rm -rf build dist *.egg-info

      - name: Build package (sdist + wheel)
        run: python -m build

      - name: Twine check
        run: twine check dist/*

      # If triggered by a tag (e.g. release), verify tag == pyproject version
      - name: Verify version matches tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PYV=$(python - <<'PY'
import tomllib, sys
with open("pyproject.toml","rb") as f:
    print(tomllib.load(f)["project"]["version"])
PY
)
          echo "Tag: $TAG  PyProject: $PYV"
          [ "$TAG" = "$PYV" ] || { echo "Version mismatch"; exit 1; }

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
